#!/usr/bin/env bash

TRACKPAD_DEVICE_ID=$(cat ~/.config/magic-trackpad-switcher/TRACKPAD_DEVICE_ID)

while :
do
  IS_POWER_ON=$(blueutil --power | grep 1)
  if [ "$IS_POWER_ON" ]; then
    # Pair the trackpad if it is not paired.
    IS_TRACKPAD_PAIRED=$(blueutil --paired | grep $TRACKPAD_DEVICE_ID)
    if [ ! "$IS_TRACKPAD_PAIRED" ]; then
      blueutil --pair $TRACKPAD_DEVICE_ID
      blueutil --wait-connect $TRACKPAD_DEVICE_ID
    fi

    # Wait for trackpad to be disconnected.
    blueutil --wait-disconnect $TRACKPAD_DEVICE_ID
    blueutil --unpair $TRACKPAD_DEVICE_ID
  else
    #  When the bluetooth module is off, just wait. While waiting, the system sleeps.
    sleep 5
  fi
done
