name: Release
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fwal/setup-swift@v1
        with:
          swift-version: '5'
      - name: Build
        run: xcrun swift build -c release --arch arm64 --arch x86_64
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: .build/apple/Products/Release/magic-trackpad-switcher
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.PAT }}
          tap: mizdra/tap
          formula: magic-trackpad-switcher
          livecheck: true
